### ISSUE TITLE
Investigate unknown/unknown arch  in the Docker builds

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2654]
# 🎯 Problem to be solved
An `unknown/unknown` arch is showing up in the Docker builds. It should be related to the lack of version pinning for `buildkit` and `buildx` in the GitHub Actions workflow for `ObolNetwork/charon`. See the discussion [here](https://github.com/orgs/community/discussions/45969).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE51QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e35e38e23a0892c6a5f0262023e3a69d246327a/image.png)

## 🛠️ Proposed solution
- [ ] Investigate the `unknown/unknown` arch issue to confirm that it's related to version pinning of `buildkit` and `buildx`.
- [ ] Update `build-push-deploy.yml` GitHub Actions workflow with version pinning:
  - Option 1: Pin Docker `Buildx` and `buildkit` versions, See [Version Pinning](https://docs.docker.com/build/ci/github-actions/configure-builder/#version-pinning).
    ```yaml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:v0.11.0
    ```
  - Option 2: Add an environment variable to disable default attestations. See [disable the default provenance attestations](https://docs.docker.com/build/building/env-vars/#buildx_no_default_attestations).
    ```yaml
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    ```
We should go for the 2nd option first, since seems less intrusive.
