### ISSUE TITLE
Add no-issue PRs to project board

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#987]
## Problem to be solved

We track what we do in sprints via the Obol org level github project. This is currently done mostly for issues, so PRs linked to issues are tracked, but PRs not linked to issues are not tracked,

We want to track more work done during sprints, specifically PRs not linked to issues.  

## Proposed solution

Write a github action that adds no-issue PRs to the project board for current sprint with size 1.
- Trigger the action when PRs are closed (since the issue can be linked after creation)
- Write a custom go tool that does the following (see verifypr as example).
- Ensure the PR body doesn't contain a link to an issue (regex), if it does, do nothing
- Add the PR to the "Obol Network Project Management" project for current sprint and size 1.
- Ensure it works well with other issues in the project and sprints and planning in general

### Out of Scope

We do not want to change the current dev workflow, specifically:
 - We still want to allow multiple PRs per issue (micro-commits FTW!)
 - We still want to allow small quick PRs to be done without tickets (more coding FTW!)

This can be improved by:
 - Adding it to other repos maybe?
 - Check for link in attached "development" metadata. 
 - Increasing size based on number of lines changed (e.g. 1 < 100 or 2 < 500 else 3)

**Comment by thomasheremans** [comment]
Hey @xenowits , I had started working on it and this action was almost working. I was just missing the syntax to check whether the linked issues was empty. We can probably add this code to the existing action to add issues to the project as very similar. Still need to add the size 1 aspect tho.

```
# This is a basic workflow adding closed PR in this repo to the new Project Management Board
name: Add Issue To Project

# Controls when the workflow will run - closed PRs
on:
  pull_request:
    types:
      - closed

# This workflow contains a single job called "build"
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Add PR To Project

       ## This is what I was struggling with
        if: ${{ github.event_name == 'pull_request' && not(github.event.pull_request.closingIssuesReferences)}}
        
        uses: actions/add-to-project@v0.3.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/thomasheremans/projects/1
          # A GitHub personal access token with write access to the project, need org admin's token with repo and project permissions, need to store the token outside the script if public
          github-token: <TOKEN>
```
